name: deseq2_norm_qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-deseq2=1.42.0
  - bioconductor-biobase=2.62.0
  - bioconductor-poiclaclu=1.0.2.1
  - r-tidyverse=2.0.0
  - r-rfast=2.0.8
  - r-rcolorbrewer=1.1_3
  - r-factoextra=1.0.7
  - r-gplots=3.1.3
  - r-ggrepel=0.9.4
  - r-pheatmap=1.0.12
  - r-scatterplot3d=0.3_44
  - r-plotly=4.10.3
  - r-htmlwidgets=1.6.2
  - r-corrplot=0.92
  - r-fitdistrplus=1.1_11
  - r-fnn=1.1.3.2
  - r-igraph=1.5.1
  - r-dendsort=0.3.4
  - r-viridis=0.6.4
  - r-uwot=0.1.16
  - r-optparse=1.7.3