name: tximport
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-tximport=1.30.0
  - bioconductor-genomicfeatures=1.54.1
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-rsamtools=2.18.0
  - bioconductor-genomicalignments=1.38.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-rsubread=2.16.1
  - r-tidyverse=2.0.0
  - r-optparse=1.7.3
  - r-knitr=1.44
  - r-rmarkdown=2.25